name: Deploy waally-backend

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Se connecter au VPS et déployer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            cd /var/www/project/laravel/waally-backend

            # Vérifier la branche et pull le bon code
            BRANCH=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
            git fetch --all
            git reset --hard origin/$BRANCH

            # Installer les dépendances Laravel
            composer install --no-dev --optimize-autoloader

            # Mettre à jour l'environnement
            cp .env.${BRANCH} .env

            # Mettre à jour les variables de connexion à la base de données selon la branche
            if [ "$BRANCH" == "dev" ]; then
              echo "DB_CONNECTION=mysql" >> .env
              echo "DB_HOST=${{ secrets.DB_TEST_HOST }}" >> .env
              echo "DB_USERNAME=${{ secrets.DB_TEST_USERNAME }}" >> .env
              echo "DB_PASSWORD=${{ secrets.DB_TEST_PASSWORD }}" >> .env
              echo "DB_DATABASE=${{ secrets.DB_TEST_DATABASE }}" >> .env
            elif [ "$BRANCH" == "main" ]; then
              echo "DB_CONNECTION=mysql" >> .env
              echo "DB_HOST=${{ secrets.DB_PROD_HOST }}" >> .env
              echo "DB_USERNAME=${{ secrets.DB_PROD_USERNAME }}" >> .env
              echo "DB_PASSWORD=${{ secrets.DB_PROD_PASSWORD }}" >> .env
              echo "DB_DATABASE=${{ secrets.DB_PROD_DATABASE }}" >> .env
            fi

            # Exécuter les migrations
            php artisan migrate --force

            # Donner les permissions correctes
            chmod -R 775 storage bootstrap/cache

            # Redémarrer les services (si nécessaire)
            sudo systemctl restart nginx
            sudo systemctl restart php8.1-fpm
